spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:1809/
          predicates:
            - Path= /customers/**
        - id: r2
          uri: http://localhost:2023/
          predicates:
            - Path= /products/**